/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LocaleIndexImport } from './routes/$locale/index'
import { Route as LocaleCreateTeamImport } from './routes/$locale/create-team'
import { Route as LocaleAiImport } from './routes/$locale/ai'
import { Route as LocaleTeamIdImport } from './routes/$locale/$teamId'
import { Route as LocaleTeamIdAdminImport } from './routes/$locale/$teamId/admin'
import { Route as LocaleTeamIdLearnerIndexImport } from './routes/$locale/$teamId/learner/index'
import { Route as LocaleTeamIdAdminIndexImport } from './routes/$locale/$teamId/admin/index'
import { Route as LocaleTeamIdAdminSettingsImport } from './routes/$locale/$teamId/admin/settings'
import { Route as LocaleTeamIdAdminOnboardImport } from './routes/$locale/$teamId/admin/onboard'
import { Route as LocaleTeamIdAdminMembersImport } from './routes/$locale/$teamId/admin/members'
import { Route as LocaleTeamIdAdminKeysImport } from './routes/$locale/$teamId/admin/keys'
import { Route as LocaleTeamIdAdminCertificateImport } from './routes/$locale/$teamId/admin/certificate'
import { Route as LocaleTeamIdAdminCoursesCreateImport } from './routes/$locale/$teamId/admin/courses/create'
import { Route as LocaleTeamIdAdminCollectionsCreateImport } from './routes/$locale/$teamId/admin/collections/create'
import { Route as LocaleTeamIdLearnerCoursesCourseIdIndexImport } from './routes/$locale/$teamId/learner/courses/$courseId/index'
import { Route as LocaleTeamIdLearnerCollectionsCollectionIdIndexImport } from './routes/$locale/$teamId/learner/collections/$collectionId/index'
import { Route as LocaleTeamIdLearnerCoursesCourseIdRequestImport } from './routes/$locale/$teamId/learner/courses/$courseId/request'
import { Route as LocaleTeamIdLearnerCoursesCourseIdPlayImport } from './routes/$locale/$teamId/learner/courses/$courseId/play'
import { Route as LocaleTeamIdLearnerCoursesCourseIdInviteImport } from './routes/$locale/$teamId/learner/courses/$courseId/invite'
import { Route as LocaleTeamIdLearnerCollectionsCollectionIdRequestImport } from './routes/$locale/$teamId/learner/collections/$collectionId/request'
import { Route as LocaleTeamIdLearnerCollectionsCollectionIdInviteImport } from './routes/$locale/$teamId/learner/collections/$collectionId/invite'
import { Route as LocaleTeamIdAdminCoursesIdWebhooksImport } from './routes/$locale/$teamId/admin/courses/$id/webhooks'
import { Route as LocaleTeamIdAdminCoursesIdStatisticsImport } from './routes/$locale/$teamId/admin/courses/$id/statistics'
import { Route as LocaleTeamIdAdminCoursesIdSharingImport } from './routes/$locale/$teamId/admin/courses/$id/sharing'
import { Route as LocaleTeamIdAdminCoursesIdSettingsImport } from './routes/$locale/$teamId/admin/courses/$id/settings'
import { Route as LocaleTeamIdAdminCoursesIdModulesImport } from './routes/$locale/$teamId/admin/courses/$id/modules'
import { Route as LocaleTeamIdAdminCoursesIdLearnersImport } from './routes/$locale/$teamId/admin/courses/$id/learners'
import { Route as LocaleTeamIdAdminCollectionsIdSettingsImport } from './routes/$locale/$teamId/admin/collections/$id/settings'
import { Route as LocaleTeamIdAdminCollectionsIdLearnersImport } from './routes/$locale/$teamId/admin/collections/$id/learners'
import { Route as LocaleTeamIdAdminCollectionsIdCoursesImport } from './routes/$locale/$teamId/admin/collections/$id/courses'

// Create/Update Routes

const LocaleIndexRoute = LocaleIndexImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleCreateTeamRoute = LocaleCreateTeamImport.update({
  id: '/$locale/create-team',
  path: '/$locale/create-team',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAiRoute = LocaleAiImport.update({
  id: '/$locale/ai',
  path: '/$locale/ai',
  getParentRoute: () => rootRoute,
} as any)

const LocaleTeamIdRoute = LocaleTeamIdImport.update({
  id: '/$locale/$teamId',
  path: '/$locale/$teamId',
  getParentRoute: () => rootRoute,
} as any)

const LocaleTeamIdAdminRoute = LocaleTeamIdAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleTeamIdRoute,
} as any)

const LocaleTeamIdLearnerIndexRoute = LocaleTeamIdLearnerIndexImport.update({
  id: '/learner/',
  path: '/learner/',
  getParentRoute: () => LocaleTeamIdRoute,
} as any)

const LocaleTeamIdAdminIndexRoute = LocaleTeamIdAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleTeamIdAdminRoute,
} as any)

const LocaleTeamIdAdminSettingsRoute = LocaleTeamIdAdminSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleTeamIdAdminRoute,
} as any)

const LocaleTeamIdAdminOnboardRoute = LocaleTeamIdAdminOnboardImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => LocaleTeamIdAdminRoute,
} as any)

const LocaleTeamIdAdminMembersRoute = LocaleTeamIdAdminMembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LocaleTeamIdAdminRoute,
} as any)

const LocaleTeamIdAdminKeysRoute = LocaleTeamIdAdminKeysImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => LocaleTeamIdAdminRoute,
} as any)

const LocaleTeamIdAdminCertificateRoute =
  LocaleTeamIdAdminCertificateImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCoursesCreateRoute =
  LocaleTeamIdAdminCoursesCreateImport.update({
    id: '/courses/create',
    path: '/courses/create',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCollectionsCreateRoute =
  LocaleTeamIdAdminCollectionsCreateImport.update({
    id: '/collections/create',
    path: '/collections/create',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdLearnerCoursesCourseIdIndexRoute =
  LocaleTeamIdLearnerCoursesCourseIdIndexImport.update({
    id: '/learner/courses/$courseId/',
    path: '/learner/courses/$courseId/',
    getParentRoute: () => LocaleTeamIdRoute,
  } as any)

const LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute =
  LocaleTeamIdLearnerCollectionsCollectionIdIndexImport.update({
    id: '/learner/collections/$collectionId/',
    path: '/learner/collections/$collectionId/',
    getParentRoute: () => LocaleTeamIdRoute,
  } as any)

const LocaleTeamIdLearnerCoursesCourseIdRequestRoute =
  LocaleTeamIdLearnerCoursesCourseIdRequestImport.update({
    id: '/learner/courses/$courseId/request',
    path: '/learner/courses/$courseId/request',
    getParentRoute: () => LocaleTeamIdRoute,
  } as any)

const LocaleTeamIdLearnerCoursesCourseIdPlayRoute =
  LocaleTeamIdLearnerCoursesCourseIdPlayImport.update({
    id: '/learner/courses/$courseId/play',
    path: '/learner/courses/$courseId/play',
    getParentRoute: () => LocaleTeamIdRoute,
  } as any)

const LocaleTeamIdLearnerCoursesCourseIdInviteRoute =
  LocaleTeamIdLearnerCoursesCourseIdInviteImport.update({
    id: '/learner/courses/$courseId/invite',
    path: '/learner/courses/$courseId/invite',
    getParentRoute: () => LocaleTeamIdRoute,
  } as any)

const LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute =
  LocaleTeamIdLearnerCollectionsCollectionIdRequestImport.update({
    id: '/learner/collections/$collectionId/request',
    path: '/learner/collections/$collectionId/request',
    getParentRoute: () => LocaleTeamIdRoute,
  } as any)

const LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute =
  LocaleTeamIdLearnerCollectionsCollectionIdInviteImport.update({
    id: '/learner/collections/$collectionId/invite',
    path: '/learner/collections/$collectionId/invite',
    getParentRoute: () => LocaleTeamIdRoute,
  } as any)

const LocaleTeamIdAdminCoursesIdWebhooksRoute =
  LocaleTeamIdAdminCoursesIdWebhooksImport.update({
    id: '/courses/$id/webhooks',
    path: '/courses/$id/webhooks',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCoursesIdStatisticsRoute =
  LocaleTeamIdAdminCoursesIdStatisticsImport.update({
    id: '/courses/$id/statistics',
    path: '/courses/$id/statistics',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCoursesIdSharingRoute =
  LocaleTeamIdAdminCoursesIdSharingImport.update({
    id: '/courses/$id/sharing',
    path: '/courses/$id/sharing',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCoursesIdSettingsRoute =
  LocaleTeamIdAdminCoursesIdSettingsImport.update({
    id: '/courses/$id/settings',
    path: '/courses/$id/settings',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCoursesIdModulesRoute =
  LocaleTeamIdAdminCoursesIdModulesImport.update({
    id: '/courses/$id/modules',
    path: '/courses/$id/modules',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCoursesIdLearnersRoute =
  LocaleTeamIdAdminCoursesIdLearnersImport.update({
    id: '/courses/$id/learners',
    path: '/courses/$id/learners',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCollectionsIdSettingsRoute =
  LocaleTeamIdAdminCollectionsIdSettingsImport.update({
    id: '/collections/$id/settings',
    path: '/collections/$id/settings',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCollectionsIdLearnersRoute =
  LocaleTeamIdAdminCollectionsIdLearnersImport.update({
    id: '/collections/$id/learners',
    path: '/collections/$id/learners',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

const LocaleTeamIdAdminCollectionsIdCoursesRoute =
  LocaleTeamIdAdminCollectionsIdCoursesImport.update({
    id: '/collections/$id/courses',
    path: '/collections/$id/courses',
    getParentRoute: () => LocaleTeamIdAdminRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale/$teamId': {
      id: '/$locale/$teamId'
      path: '/$locale/$teamId'
      fullPath: '/$locale/$teamId'
      preLoaderRoute: typeof LocaleTeamIdImport
      parentRoute: typeof rootRoute
    }
    '/$locale/ai': {
      id: '/$locale/ai'
      path: '/$locale/ai'
      fullPath: '/$locale/ai'
      preLoaderRoute: typeof LocaleAiImport
      parentRoute: typeof rootRoute
    }
    '/$locale/create-team': {
      id: '/$locale/create-team'
      path: '/$locale/create-team'
      fullPath: '/$locale/create-team'
      preLoaderRoute: typeof LocaleCreateTeamImport
      parentRoute: typeof rootRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale/$teamId/admin': {
      id: '/$locale/$teamId/admin'
      path: '/admin'
      fullPath: '/$locale/$teamId/admin'
      preLoaderRoute: typeof LocaleTeamIdAdminImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/admin/certificate': {
      id: '/$locale/$teamId/admin/certificate'
      path: '/certificate'
      fullPath: '/$locale/$teamId/admin/certificate'
      preLoaderRoute: typeof LocaleTeamIdAdminCertificateImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/keys': {
      id: '/$locale/$teamId/admin/keys'
      path: '/keys'
      fullPath: '/$locale/$teamId/admin/keys'
      preLoaderRoute: typeof LocaleTeamIdAdminKeysImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/members': {
      id: '/$locale/$teamId/admin/members'
      path: '/members'
      fullPath: '/$locale/$teamId/admin/members'
      preLoaderRoute: typeof LocaleTeamIdAdminMembersImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/onboard': {
      id: '/$locale/$teamId/admin/onboard'
      path: '/onboard'
      fullPath: '/$locale/$teamId/admin/onboard'
      preLoaderRoute: typeof LocaleTeamIdAdminOnboardImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/settings': {
      id: '/$locale/$teamId/admin/settings'
      path: '/settings'
      fullPath: '/$locale/$teamId/admin/settings'
      preLoaderRoute: typeof LocaleTeamIdAdminSettingsImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/': {
      id: '/$locale/$teamId/admin/'
      path: '/'
      fullPath: '/$locale/$teamId/admin/'
      preLoaderRoute: typeof LocaleTeamIdAdminIndexImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/learner/': {
      id: '/$locale/$teamId/learner/'
      path: '/learner'
      fullPath: '/$locale/$teamId/learner'
      preLoaderRoute: typeof LocaleTeamIdLearnerIndexImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/admin/collections/create': {
      id: '/$locale/$teamId/admin/collections/create'
      path: '/collections/create'
      fullPath: '/$locale/$teamId/admin/collections/create'
      preLoaderRoute: typeof LocaleTeamIdAdminCollectionsCreateImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/courses/create': {
      id: '/$locale/$teamId/admin/courses/create'
      path: '/courses/create'
      fullPath: '/$locale/$teamId/admin/courses/create'
      preLoaderRoute: typeof LocaleTeamIdAdminCoursesCreateImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/collections/$id/courses': {
      id: '/$locale/$teamId/admin/collections/$id/courses'
      path: '/collections/$id/courses'
      fullPath: '/$locale/$teamId/admin/collections/$id/courses'
      preLoaderRoute: typeof LocaleTeamIdAdminCollectionsIdCoursesImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/collections/$id/learners': {
      id: '/$locale/$teamId/admin/collections/$id/learners'
      path: '/collections/$id/learners'
      fullPath: '/$locale/$teamId/admin/collections/$id/learners'
      preLoaderRoute: typeof LocaleTeamIdAdminCollectionsIdLearnersImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/collections/$id/settings': {
      id: '/$locale/$teamId/admin/collections/$id/settings'
      path: '/collections/$id/settings'
      fullPath: '/$locale/$teamId/admin/collections/$id/settings'
      preLoaderRoute: typeof LocaleTeamIdAdminCollectionsIdSettingsImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/courses/$id/learners': {
      id: '/$locale/$teamId/admin/courses/$id/learners'
      path: '/courses/$id/learners'
      fullPath: '/$locale/$teamId/admin/courses/$id/learners'
      preLoaderRoute: typeof LocaleTeamIdAdminCoursesIdLearnersImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/courses/$id/modules': {
      id: '/$locale/$teamId/admin/courses/$id/modules'
      path: '/courses/$id/modules'
      fullPath: '/$locale/$teamId/admin/courses/$id/modules'
      preLoaderRoute: typeof LocaleTeamIdAdminCoursesIdModulesImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/courses/$id/settings': {
      id: '/$locale/$teamId/admin/courses/$id/settings'
      path: '/courses/$id/settings'
      fullPath: '/$locale/$teamId/admin/courses/$id/settings'
      preLoaderRoute: typeof LocaleTeamIdAdminCoursesIdSettingsImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/courses/$id/sharing': {
      id: '/$locale/$teamId/admin/courses/$id/sharing'
      path: '/courses/$id/sharing'
      fullPath: '/$locale/$teamId/admin/courses/$id/sharing'
      preLoaderRoute: typeof LocaleTeamIdAdminCoursesIdSharingImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/courses/$id/statistics': {
      id: '/$locale/$teamId/admin/courses/$id/statistics'
      path: '/courses/$id/statistics'
      fullPath: '/$locale/$teamId/admin/courses/$id/statistics'
      preLoaderRoute: typeof LocaleTeamIdAdminCoursesIdStatisticsImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/admin/courses/$id/webhooks': {
      id: '/$locale/$teamId/admin/courses/$id/webhooks'
      path: '/courses/$id/webhooks'
      fullPath: '/$locale/$teamId/admin/courses/$id/webhooks'
      preLoaderRoute: typeof LocaleTeamIdAdminCoursesIdWebhooksImport
      parentRoute: typeof LocaleTeamIdAdminImport
    }
    '/$locale/$teamId/learner/collections/$collectionId/invite': {
      id: '/$locale/$teamId/learner/collections/$collectionId/invite'
      path: '/learner/collections/$collectionId/invite'
      fullPath: '/$locale/$teamId/learner/collections/$collectionId/invite'
      preLoaderRoute: typeof LocaleTeamIdLearnerCollectionsCollectionIdInviteImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/learner/collections/$collectionId/request': {
      id: '/$locale/$teamId/learner/collections/$collectionId/request'
      path: '/learner/collections/$collectionId/request'
      fullPath: '/$locale/$teamId/learner/collections/$collectionId/request'
      preLoaderRoute: typeof LocaleTeamIdLearnerCollectionsCollectionIdRequestImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/learner/courses/$courseId/invite': {
      id: '/$locale/$teamId/learner/courses/$courseId/invite'
      path: '/learner/courses/$courseId/invite'
      fullPath: '/$locale/$teamId/learner/courses/$courseId/invite'
      preLoaderRoute: typeof LocaleTeamIdLearnerCoursesCourseIdInviteImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/learner/courses/$courseId/play': {
      id: '/$locale/$teamId/learner/courses/$courseId/play'
      path: '/learner/courses/$courseId/play'
      fullPath: '/$locale/$teamId/learner/courses/$courseId/play'
      preLoaderRoute: typeof LocaleTeamIdLearnerCoursesCourseIdPlayImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/learner/courses/$courseId/request': {
      id: '/$locale/$teamId/learner/courses/$courseId/request'
      path: '/learner/courses/$courseId/request'
      fullPath: '/$locale/$teamId/learner/courses/$courseId/request'
      preLoaderRoute: typeof LocaleTeamIdLearnerCoursesCourseIdRequestImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/learner/collections/$collectionId/': {
      id: '/$locale/$teamId/learner/collections/$collectionId/'
      path: '/learner/collections/$collectionId'
      fullPath: '/$locale/$teamId/learner/collections/$collectionId'
      preLoaderRoute: typeof LocaleTeamIdLearnerCollectionsCollectionIdIndexImport
      parentRoute: typeof LocaleTeamIdImport
    }
    '/$locale/$teamId/learner/courses/$courseId/': {
      id: '/$locale/$teamId/learner/courses/$courseId/'
      path: '/learner/courses/$courseId'
      fullPath: '/$locale/$teamId/learner/courses/$courseId'
      preLoaderRoute: typeof LocaleTeamIdLearnerCoursesCourseIdIndexImport
      parentRoute: typeof LocaleTeamIdImport
    }
  }
}

// Create and export the route tree

interface LocaleTeamIdAdminRouteChildren {
  LocaleTeamIdAdminCertificateRoute: typeof LocaleTeamIdAdminCertificateRoute
  LocaleTeamIdAdminKeysRoute: typeof LocaleTeamIdAdminKeysRoute
  LocaleTeamIdAdminMembersRoute: typeof LocaleTeamIdAdminMembersRoute
  LocaleTeamIdAdminOnboardRoute: typeof LocaleTeamIdAdminOnboardRoute
  LocaleTeamIdAdminSettingsRoute: typeof LocaleTeamIdAdminSettingsRoute
  LocaleTeamIdAdminIndexRoute: typeof LocaleTeamIdAdminIndexRoute
  LocaleTeamIdAdminCollectionsCreateRoute: typeof LocaleTeamIdAdminCollectionsCreateRoute
  LocaleTeamIdAdminCoursesCreateRoute: typeof LocaleTeamIdAdminCoursesCreateRoute
  LocaleTeamIdAdminCollectionsIdCoursesRoute: typeof LocaleTeamIdAdminCollectionsIdCoursesRoute
  LocaleTeamIdAdminCollectionsIdLearnersRoute: typeof LocaleTeamIdAdminCollectionsIdLearnersRoute
  LocaleTeamIdAdminCollectionsIdSettingsRoute: typeof LocaleTeamIdAdminCollectionsIdSettingsRoute
  LocaleTeamIdAdminCoursesIdLearnersRoute: typeof LocaleTeamIdAdminCoursesIdLearnersRoute
  LocaleTeamIdAdminCoursesIdModulesRoute: typeof LocaleTeamIdAdminCoursesIdModulesRoute
  LocaleTeamIdAdminCoursesIdSettingsRoute: typeof LocaleTeamIdAdminCoursesIdSettingsRoute
  LocaleTeamIdAdminCoursesIdSharingRoute: typeof LocaleTeamIdAdminCoursesIdSharingRoute
  LocaleTeamIdAdminCoursesIdStatisticsRoute: typeof LocaleTeamIdAdminCoursesIdStatisticsRoute
  LocaleTeamIdAdminCoursesIdWebhooksRoute: typeof LocaleTeamIdAdminCoursesIdWebhooksRoute
}

const LocaleTeamIdAdminRouteChildren: LocaleTeamIdAdminRouteChildren = {
  LocaleTeamIdAdminCertificateRoute: LocaleTeamIdAdminCertificateRoute,
  LocaleTeamIdAdminKeysRoute: LocaleTeamIdAdminKeysRoute,
  LocaleTeamIdAdminMembersRoute: LocaleTeamIdAdminMembersRoute,
  LocaleTeamIdAdminOnboardRoute: LocaleTeamIdAdminOnboardRoute,
  LocaleTeamIdAdminSettingsRoute: LocaleTeamIdAdminSettingsRoute,
  LocaleTeamIdAdminIndexRoute: LocaleTeamIdAdminIndexRoute,
  LocaleTeamIdAdminCollectionsCreateRoute:
    LocaleTeamIdAdminCollectionsCreateRoute,
  LocaleTeamIdAdminCoursesCreateRoute: LocaleTeamIdAdminCoursesCreateRoute,
  LocaleTeamIdAdminCollectionsIdCoursesRoute:
    LocaleTeamIdAdminCollectionsIdCoursesRoute,
  LocaleTeamIdAdminCollectionsIdLearnersRoute:
    LocaleTeamIdAdminCollectionsIdLearnersRoute,
  LocaleTeamIdAdminCollectionsIdSettingsRoute:
    LocaleTeamIdAdminCollectionsIdSettingsRoute,
  LocaleTeamIdAdminCoursesIdLearnersRoute:
    LocaleTeamIdAdminCoursesIdLearnersRoute,
  LocaleTeamIdAdminCoursesIdModulesRoute:
    LocaleTeamIdAdminCoursesIdModulesRoute,
  LocaleTeamIdAdminCoursesIdSettingsRoute:
    LocaleTeamIdAdminCoursesIdSettingsRoute,
  LocaleTeamIdAdminCoursesIdSharingRoute:
    LocaleTeamIdAdminCoursesIdSharingRoute,
  LocaleTeamIdAdminCoursesIdStatisticsRoute:
    LocaleTeamIdAdminCoursesIdStatisticsRoute,
  LocaleTeamIdAdminCoursesIdWebhooksRoute:
    LocaleTeamIdAdminCoursesIdWebhooksRoute,
}

const LocaleTeamIdAdminRouteWithChildren =
  LocaleTeamIdAdminRoute._addFileChildren(LocaleTeamIdAdminRouteChildren)

interface LocaleTeamIdRouteChildren {
  LocaleTeamIdAdminRoute: typeof LocaleTeamIdAdminRouteWithChildren
  LocaleTeamIdLearnerIndexRoute: typeof LocaleTeamIdLearnerIndexRoute
  LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute: typeof LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute
  LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute: typeof LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute
  LocaleTeamIdLearnerCoursesCourseIdInviteRoute: typeof LocaleTeamIdLearnerCoursesCourseIdInviteRoute
  LocaleTeamIdLearnerCoursesCourseIdPlayRoute: typeof LocaleTeamIdLearnerCoursesCourseIdPlayRoute
  LocaleTeamIdLearnerCoursesCourseIdRequestRoute: typeof LocaleTeamIdLearnerCoursesCourseIdRequestRoute
  LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute: typeof LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute
  LocaleTeamIdLearnerCoursesCourseIdIndexRoute: typeof LocaleTeamIdLearnerCoursesCourseIdIndexRoute
}

const LocaleTeamIdRouteChildren: LocaleTeamIdRouteChildren = {
  LocaleTeamIdAdminRoute: LocaleTeamIdAdminRouteWithChildren,
  LocaleTeamIdLearnerIndexRoute: LocaleTeamIdLearnerIndexRoute,
  LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute:
    LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute,
  LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute:
    LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute,
  LocaleTeamIdLearnerCoursesCourseIdInviteRoute:
    LocaleTeamIdLearnerCoursesCourseIdInviteRoute,
  LocaleTeamIdLearnerCoursesCourseIdPlayRoute:
    LocaleTeamIdLearnerCoursesCourseIdPlayRoute,
  LocaleTeamIdLearnerCoursesCourseIdRequestRoute:
    LocaleTeamIdLearnerCoursesCourseIdRequestRoute,
  LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute:
    LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute,
  LocaleTeamIdLearnerCoursesCourseIdIndexRoute:
    LocaleTeamIdLearnerCoursesCourseIdIndexRoute,
}

const LocaleTeamIdRouteWithChildren = LocaleTeamIdRoute._addFileChildren(
  LocaleTeamIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/$locale/$teamId': typeof LocaleTeamIdRouteWithChildren
  '/$locale/ai': typeof LocaleAiRoute
  '/$locale/create-team': typeof LocaleCreateTeamRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$teamId/admin': typeof LocaleTeamIdAdminRouteWithChildren
  '/$locale/$teamId/admin/certificate': typeof LocaleTeamIdAdminCertificateRoute
  '/$locale/$teamId/admin/keys': typeof LocaleTeamIdAdminKeysRoute
  '/$locale/$teamId/admin/members': typeof LocaleTeamIdAdminMembersRoute
  '/$locale/$teamId/admin/onboard': typeof LocaleTeamIdAdminOnboardRoute
  '/$locale/$teamId/admin/settings': typeof LocaleTeamIdAdminSettingsRoute
  '/$locale/$teamId/admin/': typeof LocaleTeamIdAdminIndexRoute
  '/$locale/$teamId/learner': typeof LocaleTeamIdLearnerIndexRoute
  '/$locale/$teamId/admin/collections/create': typeof LocaleTeamIdAdminCollectionsCreateRoute
  '/$locale/$teamId/admin/courses/create': typeof LocaleTeamIdAdminCoursesCreateRoute
  '/$locale/$teamId/admin/collections/$id/courses': typeof LocaleTeamIdAdminCollectionsIdCoursesRoute
  '/$locale/$teamId/admin/collections/$id/learners': typeof LocaleTeamIdAdminCollectionsIdLearnersRoute
  '/$locale/$teamId/admin/collections/$id/settings': typeof LocaleTeamIdAdminCollectionsIdSettingsRoute
  '/$locale/$teamId/admin/courses/$id/learners': typeof LocaleTeamIdAdminCoursesIdLearnersRoute
  '/$locale/$teamId/admin/courses/$id/modules': typeof LocaleTeamIdAdminCoursesIdModulesRoute
  '/$locale/$teamId/admin/courses/$id/settings': typeof LocaleTeamIdAdminCoursesIdSettingsRoute
  '/$locale/$teamId/admin/courses/$id/sharing': typeof LocaleTeamIdAdminCoursesIdSharingRoute
  '/$locale/$teamId/admin/courses/$id/statistics': typeof LocaleTeamIdAdminCoursesIdStatisticsRoute
  '/$locale/$teamId/admin/courses/$id/webhooks': typeof LocaleTeamIdAdminCoursesIdWebhooksRoute
  '/$locale/$teamId/learner/collections/$collectionId/invite': typeof LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute
  '/$locale/$teamId/learner/collections/$collectionId/request': typeof LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute
  '/$locale/$teamId/learner/courses/$courseId/invite': typeof LocaleTeamIdLearnerCoursesCourseIdInviteRoute
  '/$locale/$teamId/learner/courses/$courseId/play': typeof LocaleTeamIdLearnerCoursesCourseIdPlayRoute
  '/$locale/$teamId/learner/courses/$courseId/request': typeof LocaleTeamIdLearnerCoursesCourseIdRequestRoute
  '/$locale/$teamId/learner/collections/$collectionId': typeof LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute
  '/$locale/$teamId/learner/courses/$courseId': typeof LocaleTeamIdLearnerCoursesCourseIdIndexRoute
}

export interface FileRoutesByTo {
  '/$locale/$teamId': typeof LocaleTeamIdRouteWithChildren
  '/$locale/ai': typeof LocaleAiRoute
  '/$locale/create-team': typeof LocaleCreateTeamRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$teamId/admin/certificate': typeof LocaleTeamIdAdminCertificateRoute
  '/$locale/$teamId/admin/keys': typeof LocaleTeamIdAdminKeysRoute
  '/$locale/$teamId/admin/members': typeof LocaleTeamIdAdminMembersRoute
  '/$locale/$teamId/admin/onboard': typeof LocaleTeamIdAdminOnboardRoute
  '/$locale/$teamId/admin/settings': typeof LocaleTeamIdAdminSettingsRoute
  '/$locale/$teamId/admin': typeof LocaleTeamIdAdminIndexRoute
  '/$locale/$teamId/learner': typeof LocaleTeamIdLearnerIndexRoute
  '/$locale/$teamId/admin/collections/create': typeof LocaleTeamIdAdminCollectionsCreateRoute
  '/$locale/$teamId/admin/courses/create': typeof LocaleTeamIdAdminCoursesCreateRoute
  '/$locale/$teamId/admin/collections/$id/courses': typeof LocaleTeamIdAdminCollectionsIdCoursesRoute
  '/$locale/$teamId/admin/collections/$id/learners': typeof LocaleTeamIdAdminCollectionsIdLearnersRoute
  '/$locale/$teamId/admin/collections/$id/settings': typeof LocaleTeamIdAdminCollectionsIdSettingsRoute
  '/$locale/$teamId/admin/courses/$id/learners': typeof LocaleTeamIdAdminCoursesIdLearnersRoute
  '/$locale/$teamId/admin/courses/$id/modules': typeof LocaleTeamIdAdminCoursesIdModulesRoute
  '/$locale/$teamId/admin/courses/$id/settings': typeof LocaleTeamIdAdminCoursesIdSettingsRoute
  '/$locale/$teamId/admin/courses/$id/sharing': typeof LocaleTeamIdAdminCoursesIdSharingRoute
  '/$locale/$teamId/admin/courses/$id/statistics': typeof LocaleTeamIdAdminCoursesIdStatisticsRoute
  '/$locale/$teamId/admin/courses/$id/webhooks': typeof LocaleTeamIdAdminCoursesIdWebhooksRoute
  '/$locale/$teamId/learner/collections/$collectionId/invite': typeof LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute
  '/$locale/$teamId/learner/collections/$collectionId/request': typeof LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute
  '/$locale/$teamId/learner/courses/$courseId/invite': typeof LocaleTeamIdLearnerCoursesCourseIdInviteRoute
  '/$locale/$teamId/learner/courses/$courseId/play': typeof LocaleTeamIdLearnerCoursesCourseIdPlayRoute
  '/$locale/$teamId/learner/courses/$courseId/request': typeof LocaleTeamIdLearnerCoursesCourseIdRequestRoute
  '/$locale/$teamId/learner/collections/$collectionId': typeof LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute
  '/$locale/$teamId/learner/courses/$courseId': typeof LocaleTeamIdLearnerCoursesCourseIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$locale/$teamId': typeof LocaleTeamIdRouteWithChildren
  '/$locale/ai': typeof LocaleAiRoute
  '/$locale/create-team': typeof LocaleCreateTeamRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$teamId/admin': typeof LocaleTeamIdAdminRouteWithChildren
  '/$locale/$teamId/admin/certificate': typeof LocaleTeamIdAdminCertificateRoute
  '/$locale/$teamId/admin/keys': typeof LocaleTeamIdAdminKeysRoute
  '/$locale/$teamId/admin/members': typeof LocaleTeamIdAdminMembersRoute
  '/$locale/$teamId/admin/onboard': typeof LocaleTeamIdAdminOnboardRoute
  '/$locale/$teamId/admin/settings': typeof LocaleTeamIdAdminSettingsRoute
  '/$locale/$teamId/admin/': typeof LocaleTeamIdAdminIndexRoute
  '/$locale/$teamId/learner/': typeof LocaleTeamIdLearnerIndexRoute
  '/$locale/$teamId/admin/collections/create': typeof LocaleTeamIdAdminCollectionsCreateRoute
  '/$locale/$teamId/admin/courses/create': typeof LocaleTeamIdAdminCoursesCreateRoute
  '/$locale/$teamId/admin/collections/$id/courses': typeof LocaleTeamIdAdminCollectionsIdCoursesRoute
  '/$locale/$teamId/admin/collections/$id/learners': typeof LocaleTeamIdAdminCollectionsIdLearnersRoute
  '/$locale/$teamId/admin/collections/$id/settings': typeof LocaleTeamIdAdminCollectionsIdSettingsRoute
  '/$locale/$teamId/admin/courses/$id/learners': typeof LocaleTeamIdAdminCoursesIdLearnersRoute
  '/$locale/$teamId/admin/courses/$id/modules': typeof LocaleTeamIdAdminCoursesIdModulesRoute
  '/$locale/$teamId/admin/courses/$id/settings': typeof LocaleTeamIdAdminCoursesIdSettingsRoute
  '/$locale/$teamId/admin/courses/$id/sharing': typeof LocaleTeamIdAdminCoursesIdSharingRoute
  '/$locale/$teamId/admin/courses/$id/statistics': typeof LocaleTeamIdAdminCoursesIdStatisticsRoute
  '/$locale/$teamId/admin/courses/$id/webhooks': typeof LocaleTeamIdAdminCoursesIdWebhooksRoute
  '/$locale/$teamId/learner/collections/$collectionId/invite': typeof LocaleTeamIdLearnerCollectionsCollectionIdInviteRoute
  '/$locale/$teamId/learner/collections/$collectionId/request': typeof LocaleTeamIdLearnerCollectionsCollectionIdRequestRoute
  '/$locale/$teamId/learner/courses/$courseId/invite': typeof LocaleTeamIdLearnerCoursesCourseIdInviteRoute
  '/$locale/$teamId/learner/courses/$courseId/play': typeof LocaleTeamIdLearnerCoursesCourseIdPlayRoute
  '/$locale/$teamId/learner/courses/$courseId/request': typeof LocaleTeamIdLearnerCoursesCourseIdRequestRoute
  '/$locale/$teamId/learner/collections/$collectionId/': typeof LocaleTeamIdLearnerCollectionsCollectionIdIndexRoute
  '/$locale/$teamId/learner/courses/$courseId/': typeof LocaleTeamIdLearnerCoursesCourseIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale/$teamId'
    | '/$locale/ai'
    | '/$locale/create-team'
    | '/$locale'
    | '/$locale/$teamId/admin'
    | '/$locale/$teamId/admin/certificate'
    | '/$locale/$teamId/admin/keys'
    | '/$locale/$teamId/admin/members'
    | '/$locale/$teamId/admin/onboard'
    | '/$locale/$teamId/admin/settings'
    | '/$locale/$teamId/admin/'
    | '/$locale/$teamId/learner'
    | '/$locale/$teamId/admin/collections/create'
    | '/$locale/$teamId/admin/courses/create'
    | '/$locale/$teamId/admin/collections/$id/courses'
    | '/$locale/$teamId/admin/collections/$id/learners'
    | '/$locale/$teamId/admin/collections/$id/settings'
    | '/$locale/$teamId/admin/courses/$id/learners'
    | '/$locale/$teamId/admin/courses/$id/modules'
    | '/$locale/$teamId/admin/courses/$id/settings'
    | '/$locale/$teamId/admin/courses/$id/sharing'
    | '/$locale/$teamId/admin/courses/$id/statistics'
    | '/$locale/$teamId/admin/courses/$id/webhooks'
    | '/$locale/$teamId/learner/collections/$collectionId/invite'
    | '/$locale/$teamId/learner/collections/$collectionId/request'
    | '/$locale/$teamId/learner/courses/$courseId/invite'
    | '/$locale/$teamId/learner/courses/$courseId/play'
    | '/$locale/$teamId/learner/courses/$courseId/request'
    | '/$locale/$teamId/learner/collections/$collectionId'
    | '/$locale/$teamId/learner/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale/$teamId'
    | '/$locale/ai'
    | '/$locale/create-team'
    | '/$locale'
    | '/$locale/$teamId/admin/certificate'
    | '/$locale/$teamId/admin/keys'
    | '/$locale/$teamId/admin/members'
    | '/$locale/$teamId/admin/onboard'
    | '/$locale/$teamId/admin/settings'
    | '/$locale/$teamId/admin'
    | '/$locale/$teamId/learner'
    | '/$locale/$teamId/admin/collections/create'
    | '/$locale/$teamId/admin/courses/create'
    | '/$locale/$teamId/admin/collections/$id/courses'
    | '/$locale/$teamId/admin/collections/$id/learners'
    | '/$locale/$teamId/admin/collections/$id/settings'
    | '/$locale/$teamId/admin/courses/$id/learners'
    | '/$locale/$teamId/admin/courses/$id/modules'
    | '/$locale/$teamId/admin/courses/$id/settings'
    | '/$locale/$teamId/admin/courses/$id/sharing'
    | '/$locale/$teamId/admin/courses/$id/statistics'
    | '/$locale/$teamId/admin/courses/$id/webhooks'
    | '/$locale/$teamId/learner/collections/$collectionId/invite'
    | '/$locale/$teamId/learner/collections/$collectionId/request'
    | '/$locale/$teamId/learner/courses/$courseId/invite'
    | '/$locale/$teamId/learner/courses/$courseId/play'
    | '/$locale/$teamId/learner/courses/$courseId/request'
    | '/$locale/$teamId/learner/collections/$collectionId'
    | '/$locale/$teamId/learner/courses/$courseId'
  id:
    | '__root__'
    | '/$locale/$teamId'
    | '/$locale/ai'
    | '/$locale/create-team'
    | '/$locale/'
    | '/$locale/$teamId/admin'
    | '/$locale/$teamId/admin/certificate'
    | '/$locale/$teamId/admin/keys'
    | '/$locale/$teamId/admin/members'
    | '/$locale/$teamId/admin/onboard'
    | '/$locale/$teamId/admin/settings'
    | '/$locale/$teamId/admin/'
    | '/$locale/$teamId/learner/'
    | '/$locale/$teamId/admin/collections/create'
    | '/$locale/$teamId/admin/courses/create'
    | '/$locale/$teamId/admin/collections/$id/courses'
    | '/$locale/$teamId/admin/collections/$id/learners'
    | '/$locale/$teamId/admin/collections/$id/settings'
    | '/$locale/$teamId/admin/courses/$id/learners'
    | '/$locale/$teamId/admin/courses/$id/modules'
    | '/$locale/$teamId/admin/courses/$id/settings'
    | '/$locale/$teamId/admin/courses/$id/sharing'
    | '/$locale/$teamId/admin/courses/$id/statistics'
    | '/$locale/$teamId/admin/courses/$id/webhooks'
    | '/$locale/$teamId/learner/collections/$collectionId/invite'
    | '/$locale/$teamId/learner/collections/$collectionId/request'
    | '/$locale/$teamId/learner/courses/$courseId/invite'
    | '/$locale/$teamId/learner/courses/$courseId/play'
    | '/$locale/$teamId/learner/courses/$courseId/request'
    | '/$locale/$teamId/learner/collections/$collectionId/'
    | '/$locale/$teamId/learner/courses/$courseId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LocaleTeamIdRoute: typeof LocaleTeamIdRouteWithChildren
  LocaleAiRoute: typeof LocaleAiRoute
  LocaleCreateTeamRoute: typeof LocaleCreateTeamRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LocaleTeamIdRoute: LocaleTeamIdRouteWithChildren,
  LocaleAiRoute: LocaleAiRoute,
  LocaleCreateTeamRoute: LocaleCreateTeamRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$locale/$teamId",
        "/$locale/ai",
        "/$locale/create-team",
        "/$locale/"
      ]
    },
    "/$locale/$teamId": {
      "filePath": "$locale/$teamId.tsx",
      "children": [
        "/$locale/$teamId/admin",
        "/$locale/$teamId/learner/",
        "/$locale/$teamId/learner/collections/$collectionId/invite",
        "/$locale/$teamId/learner/collections/$collectionId/request",
        "/$locale/$teamId/learner/courses/$courseId/invite",
        "/$locale/$teamId/learner/courses/$courseId/play",
        "/$locale/$teamId/learner/courses/$courseId/request",
        "/$locale/$teamId/learner/collections/$collectionId/",
        "/$locale/$teamId/learner/courses/$courseId/"
      ]
    },
    "/$locale/ai": {
      "filePath": "$locale/ai.tsx"
    },
    "/$locale/create-team": {
      "filePath": "$locale/create-team.tsx"
    },
    "/$locale/": {
      "filePath": "$locale/index.tsx"
    },
    "/$locale/$teamId/admin": {
      "filePath": "$locale/$teamId/admin.tsx",
      "parent": "/$locale/$teamId",
      "children": [
        "/$locale/$teamId/admin/certificate",
        "/$locale/$teamId/admin/keys",
        "/$locale/$teamId/admin/members",
        "/$locale/$teamId/admin/onboard",
        "/$locale/$teamId/admin/settings",
        "/$locale/$teamId/admin/",
        "/$locale/$teamId/admin/collections/create",
        "/$locale/$teamId/admin/courses/create",
        "/$locale/$teamId/admin/collections/$id/courses",
        "/$locale/$teamId/admin/collections/$id/learners",
        "/$locale/$teamId/admin/collections/$id/settings",
        "/$locale/$teamId/admin/courses/$id/learners",
        "/$locale/$teamId/admin/courses/$id/modules",
        "/$locale/$teamId/admin/courses/$id/settings",
        "/$locale/$teamId/admin/courses/$id/sharing",
        "/$locale/$teamId/admin/courses/$id/statistics",
        "/$locale/$teamId/admin/courses/$id/webhooks"
      ]
    },
    "/$locale/$teamId/admin/certificate": {
      "filePath": "$locale/$teamId/admin/certificate.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/keys": {
      "filePath": "$locale/$teamId/admin/keys.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/members": {
      "filePath": "$locale/$teamId/admin/members.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/onboard": {
      "filePath": "$locale/$teamId/admin/onboard.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/settings": {
      "filePath": "$locale/$teamId/admin/settings.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/": {
      "filePath": "$locale/$teamId/admin/index.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/learner/": {
      "filePath": "$locale/$teamId/learner/index.tsx",
      "parent": "/$locale/$teamId"
    },
    "/$locale/$teamId/admin/collections/create": {
      "filePath": "$locale/$teamId/admin/collections/create.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/courses/create": {
      "filePath": "$locale/$teamId/admin/courses/create.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/collections/$id/courses": {
      "filePath": "$locale/$teamId/admin/collections/$id/courses.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/collections/$id/learners": {
      "filePath": "$locale/$teamId/admin/collections/$id/learners.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/collections/$id/settings": {
      "filePath": "$locale/$teamId/admin/collections/$id/settings.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/courses/$id/learners": {
      "filePath": "$locale/$teamId/admin/courses/$id/learners.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/courses/$id/modules": {
      "filePath": "$locale/$teamId/admin/courses/$id/modules.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/courses/$id/settings": {
      "filePath": "$locale/$teamId/admin/courses/$id/settings.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/courses/$id/sharing": {
      "filePath": "$locale/$teamId/admin/courses/$id/sharing.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/courses/$id/statistics": {
      "filePath": "$locale/$teamId/admin/courses/$id/statistics.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/admin/courses/$id/webhooks": {
      "filePath": "$locale/$teamId/admin/courses/$id/webhooks.tsx",
      "parent": "/$locale/$teamId/admin"
    },
    "/$locale/$teamId/learner/collections/$collectionId/invite": {
      "filePath": "$locale/$teamId/learner/collections/$collectionId/invite.tsx",
      "parent": "/$locale/$teamId"
    },
    "/$locale/$teamId/learner/collections/$collectionId/request": {
      "filePath": "$locale/$teamId/learner/collections/$collectionId/request.tsx",
      "parent": "/$locale/$teamId"
    },
    "/$locale/$teamId/learner/courses/$courseId/invite": {
      "filePath": "$locale/$teamId/learner/courses/$courseId/invite.tsx",
      "parent": "/$locale/$teamId"
    },
    "/$locale/$teamId/learner/courses/$courseId/play": {
      "filePath": "$locale/$teamId/learner/courses/$courseId/play.tsx",
      "parent": "/$locale/$teamId"
    },
    "/$locale/$teamId/learner/courses/$courseId/request": {
      "filePath": "$locale/$teamId/learner/courses/$courseId/request.tsx",
      "parent": "/$locale/$teamId"
    },
    "/$locale/$teamId/learner/collections/$collectionId/": {
      "filePath": "$locale/$teamId/learner/collections/$collectionId/index.tsx",
      "parent": "/$locale/$teamId"
    },
    "/$locale/$teamId/learner/courses/$courseId/": {
      "filePath": "$locale/$teamId/learner/courses/$courseId/index.tsx",
      "parent": "/$locale/$teamId"
    }
  }
}
ROUTE_MANIFEST_END */
